_BASE_: "../Base-Distillation.yaml"
OUTPUT_DIR: output/PAT-MV2-SwinT
INPUT:
  FORMAT: "BGR"
MODEL:
  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [1.0, 1.0, 1.0]  # PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_mobilenetv2_fpn_backbone"
    FREEZE_AT: 0
  WEIGHTS: "pretrained/mv2-swint.pth"
  MOBILENETV2:
    OUT_FEATURES: ["m2", "m3", "m4", "m5"]
  FPN:
    IN_FEATURES: ["m2", "m3", "m4", "m5"]
  PROPOSAL_GENERATOR:
    NAME: "RPN"
  ROI_HEADS:
    NAME: "StandardROIHeads"

TEACHER:
  MODEL:
    WEIGHTS: "pretrained/faster_rcnn_swint_T.pth"
    PIXEL_MEAN: [103.53, 116.28, 123.675]
    PIXEL_STD: [1.0, 1.0, 1.0] # I use the dafault config PIXEL_MEAN, PIXEL_STD, INPUT.FORMAT , that is a mistake, but it affects performance negligently.
    MASK_ON: False
    RESNETS:
      DEPTH: 50
    BACKBONE:
      NAME: "build_swint_fpn_backbone"
    SWINT:
      OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
    FPN:
      IN_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
  KD:
    TYPE: "PAT"
    PAT:
      STAGE: [0, 1, 2, 3]

KD:
  TYPE: "PAT"
  PAT:
    MSE_LOSS_WEIGHT: 1.0
    REG_LOSS_WEIGHT: 1.0
    GT_LOSS_WEIGHT: 1.0
    KD_LOSS_WEIGHT: 1.0
    TEMPERATURE: 1.0
    RAA_NUM_QUERIES: 125
    RAA_DIM: 64

SOLVER:
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  MAX_ITER: 270000
  STEPS:
  - 210000
  - 250000
